### ISSUE TITLE
Potential crash due to finalization race condition

### ISSUE THREAD

**Issue by itsff** [xamarin/flex#3] opened 2017-09-15 05:53 UTC
The `Item` class has a `~` finalizer which cleans up the native resource. The finalizer will get invoked on a different thread after the `Item` object instance has been garbage collected. A potential problem can arise when running in release mode, where the runtime employs more aggressive optimizations. Unlike in C/C++ where objects get disposed when they go out of scope, in .NET objects are eligible for garbage collection when they are no longer utilized - no matter the scope (example: a big array is used _only_ at the beginning of a method, so why wait until method exits before GCing the array?).

A contrived example:

```C#
void someMethod ()
{
    var xyz = new Item();
    xyz.Height = 100; 
    // ^^^^^ This can crash while we're in Item::flex_item_set_height(item, value);
}
```

In the example above, the `xyz` instance becomes eligible for GC when it's no longer needed, which is right after its `this` pointer got referenced for reading the value of `item` within `Item::Height::set`. So it's possible the finalizer thread will invoke `~Item` while the `flex_item_set_height` is still executing. Obviously not a good thing.

Two choices here: 

1. Continue using the `~` finalizer and rely on `GC.KeepAlive(this)` to keep your `Item` instance alive until you're done calling native functions.
https://goo.gl/WeL3H4
https://msdn.microsoft.com/en-us/library/ms182300.aspx
https://blogs.msdn.microsoft.com/oldnewthing/20100813-00/?p=13153

2. Ditch the `~` finalizer and switch to `SafeHandle`s. Instead of using `IntPtr` derive from `SafeHandle` (or from `SafeHandleZeroOrMinusOneIsInvalid`) and move the destruction logic to `SafeHandle::ReleaseHandle`. The runtime treats `SafeHandles` in a special way, so they won't be finalized while the native code is being executed.

**Comment by itsff** [comment] 2017-09-15 16:45
FYI: https://github.com/facebook/yoga/issues/295

**Comment by Phrohdoh** [comment] 2017-09-21 13:39
Pardon my ignorance here but how is the `this` ptr for `xyz` "no longer needed" when calling an instance method (the setter)?

**Comment by itsff** [comment] 2017-09-21 14:23
Yep, essentially that. The this pointer is only needed to resolve the member variable. 
It's one of the challenges doing mixed (native/managed) development - the runtime is only aware of half of the equation and we need to help it along. The `SafeHandle` approach should work fine in this case (as it did with yoga) with minimum code changes.

**Comment by lrz** [comment] 2017-10-02 12:30
Thanks for filing this issue. As of master we are now following the IDisposable pattern, so I'm closing this ticket as I believe the problem is no longer present.

**Closed by lrz** 2017-10-02 12:30 UTC

**Comment by itsff** [comment] 2017-10-09 17:01
Removing the `~` finalizer does fix the potential of crash due to a race condition, but now there is a possibility of a memory leak. What happens if user creates a new `Item` but forgets to call `Dispose` (most .NET developers do this)? The native memory will never be reclaimed...
